DEBUG 2024-09-11 13:57:41.136 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-11 13:57:41.137 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-11 13:57:41.137 UTC: 	 Executing command: 'submit'
DEBUG 2024-09-11 13:57:41.137 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
INFO 2024-09-11 13:57:41.140 UTC: 	 Will use CRAB configuration file crab_config.py
DEBUG 2024-09-11 13:57:41.140 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-09-11 13:57:41.145 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-09-11 13:57:41.145 UTC: 	 Working area '/gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_2022C' already exists 
Please change the requestName in the config file
ERROR 2024-09-11 13:57:41.145 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 327, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_2022C' already exists 
Please change the requestName in the config file
INFO 2024-09-11 13:57:41.156 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-11 15:25:42.693 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-11 15:25:42.693 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-11 15:25:42.693 UTC: 	 Executing command: 'checkusername'
DEBUG 2024-09-11 15:25:42.694 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
DEBUG 2024-09-11 15:25:42.696 UTC: 	 Checking credentials
DEBUG 2024-09-11 15:25:42.696 UTC: 	 Found proxy file /tmp/x509up_u2414
DEBUG 2024-09-11 15:25:42.696 UTC: 	 Making sure it has proper VOMS extension
DEBUG 2024-09-11 15:25:42.697 UTC: 	 Executing command :
 voms-proxy-info --vo --file /tmp/x509up_u2414
DEBUG 2024-09-11 15:25:43.463 UTC: 	 output : cms

 error: 
 retcode : 0
DEBUG 2024-09-11 15:25:43.463 UTC: 	 Getting proxy life time left
DEBUG 2024-09-11 15:25:43.463 UTC: 	 Executing command :
 voms-proxy-info --actimeleft --timeleft --file /tmp/x509up_u2414
DEBUG 2024-09-11 15:25:44.196 UTC: 	 output : 247550
247550

 error: 
 retcode : 0
DEBUG 2024-09-11 15:25:44.196 UTC: 	 Proxy valid for 68:45:50 hours
DEBUG 2024-09-11 15:25:44.196 UTC: 	 Command use: checkusername
DEBUG 2024-09-11 15:25:44.196 UTC: 	 Options use: []
DEBUG 2024-09-11 15:25:44.196 UTC: 	 Instance is None
DEBUG 2024-09-11 15:25:44.196 UTC: 	 Server base url is None
DEBUG 2024-09-11 15:25:44.196 UTC: 	 Retrieving username ...
DEBUG 2024-09-11 15:25:44.196 UTC: 	 Retrieving username from CRIC...
DEBUG 2024-09-11 15:25:44.928 UTC: 	 username is damram
INFO 2024-09-11 15:25:44.928 UTC: 	 Username is: damram
DEBUG 2024-09-11 15:26:42.359 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-11 15:26:42.360 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-11 15:26:42.360 UTC: 	 Executing command: 'checkusername'
DEBUG 2024-09-11 15:26:42.360 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
DEBUG 2024-09-11 15:26:42.362 UTC: 	 Checking credentials
DEBUG 2024-09-11 15:26:42.362 UTC: 	 Found proxy file /tmp/x509up_u2414
DEBUG 2024-09-11 15:26:42.362 UTC: 	 Making sure it has proper VOMS extension
DEBUG 2024-09-11 15:26:42.362 UTC: 	 Executing command :
 voms-proxy-info --vo --file /tmp/x509up_u2414
DEBUG 2024-09-11 15:26:43.153 UTC: 	 output : cms

 error: 
 retcode : 0
DEBUG 2024-09-11 15:26:43.153 UTC: 	 Getting proxy life time left
DEBUG 2024-09-11 15:26:43.153 UTC: 	 Executing command :
 voms-proxy-info --actimeleft --timeleft --file /tmp/x509up_u2414
DEBUG 2024-09-11 15:26:43.890 UTC: 	 output : 691192
691192

 error: 
 retcode : 0
DEBUG 2024-09-11 15:26:43.891 UTC: 	 Proxy valid for 191:59:52 hours
DEBUG 2024-09-11 15:26:43.891 UTC: 	 Command use: checkusername
DEBUG 2024-09-11 15:26:43.891 UTC: 	 Options use: []
DEBUG 2024-09-11 15:26:43.891 UTC: 	 Instance is None
DEBUG 2024-09-11 15:26:43.891 UTC: 	 Server base url is None
DEBUG 2024-09-11 15:26:43.891 UTC: 	 Retrieving username ...
DEBUG 2024-09-11 15:26:43.891 UTC: 	 Retrieving username from CRIC...
DEBUG 2024-09-11 15:26:44.657 UTC: 	 username is damram
INFO 2024-09-11 15:26:44.658 UTC: 	 Username is: damram
DEBUG 2024-09-12 10:17:25.921 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-12 10:17:25.921 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-12 10:17:25.921 UTC: 	 Executing command: 'submit'
DEBUG 2024-09-12 10:17:25.921 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
ERROR 2024-09-12 10:17:25.922 UTC: 	 CRAB configuration file crab_config.py not found.
ERROR 2024-09-12 10:17:25.922 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 325, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 53, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
CRABClient.ClientExceptions.ConfigurationException: CRAB configuration file crab_config.py not found.
INFO 2024-09-12 10:17:25.947 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-12 10:17:48.028 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-12 10:17:48.028 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-12 10:17:48.028 UTC: 	 Executing command: 'submit'
DEBUG 2024-09-12 10:17:48.028 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
INFO 2024-09-12 10:17:48.029 UTC: 	 Will use CRAB configuration file crab_config_data.py
DEBUG 2024-09-12 10:17:48.029 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-09-12 10:17:48.036 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-09-12 10:17:48.036 UTC: 	 Working area '/gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_2022C' already exists 
Please change the requestName in the config file
ERROR 2024-09-12 10:17:48.037 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 327, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_2022C' already exists 
Please change the requestName in the config file
INFO 2024-09-12 10:17:48.043 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-12 19:09:50.423 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-12 19:09:50.423 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-12 19:09:50.423 UTC: 	 Executing command: 'checkwrite'
DEBUG 2024-09-12 19:09:50.424 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
DEBUG 2024-09-12 19:09:50.426 UTC: 	 Checking credentials
DEBUG 2024-09-12 19:09:50.426 UTC: 	 Found proxy file /tmp/x509up_u2414
DEBUG 2024-09-12 19:09:50.426 UTC: 	 Making sure it has proper VOMS extension
DEBUG 2024-09-12 19:09:50.426 UTC: 	 Executing command :
 voms-proxy-info --vo --file /tmp/x509up_u2414
DEBUG 2024-09-12 19:09:51.175 UTC: 	 output : cms

 error: 
 retcode : 0
DEBUG 2024-09-12 19:09:51.175 UTC: 	 Getting proxy life time left
DEBUG 2024-09-12 19:09:51.175 UTC: 	 Executing command :
 voms-proxy-info --actimeleft --timeleft --file /tmp/x509up_u2414
DEBUG 2024-09-12 19:09:51.936 UTC: 	 output : 691180
691180

 error: 
 retcode : 0
DEBUG 2024-09-12 19:09:51.936 UTC: 	 Proxy valid for 191:59:40 hours
DEBUG 2024-09-12 19:09:51.937 UTC: 	 Retrieving username ...
DEBUG 2024-09-12 19:09:51.937 UTC: 	 Retrieving username from CRIC...
DEBUG 2024-09-12 19:09:52.721 UTC: 	 username is damram
INFO 2024-09-12 19:09:53.646 UTC: 	 Rucio client intialized for account damram
DEBUG 2024-09-12 19:09:53.646 UTC: 	 Command use: checkwrite
DEBUG 2024-09-12 19:09:53.646 UTC: 	 Options use: ['--site=T3_FR_IPNL']
DEBUG 2024-09-12 19:09:53.646 UTC: 	 Instance is None
DEBUG 2024-09-12 19:09:53.646 UTC: 	 Server base url is None
DEBUG 2024-09-12 19:09:53.646 UTC: 	 Retrieving username ...
DEBUG 2024-09-12 19:09:53.646 UTC: 	 Retrieving username from CRIC...
DEBUG 2024-09-12 19:09:54.276 UTC: 	 username is damram
INFO 2024-09-12 19:09:54.276 UTC: 	 Will check write permission in the default location /store/user/<username>
INFO 2024-09-12 19:09:54.276 UTC: 	 Validating LFN /store/user/damram...
INFO 2024-09-12 19:09:54.277 UTC: 	 LFN /store/user/damram is valid.
INFO 2024-09-12 19:09:54.314 UTC: 	 Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
INFO 2024-09-12 19:09:54.314 UTC: 	 Will check write permission in /store/user/damram on site T3_FR_IPNL
INFO 2024-09-12 19:09:54.340 UTC: 	 Will use PFN: root://lyoeos.in2p3.fr:1094//store/user/damram/crab3checkwrite_20240912_210954_18be249b-fedf-4f54-a3ee-3275532e4221/18be249b-fedf-4f54-a3ee-3275532e4221.tmp
INFO 2024-09-12 19:09:54.340 UTC: 	 
Attempting to create (dummy) directory crab3checkwrite_20240912_210954_18be249b-fedf-4f54-a3ee-3275532e4221 and copy (dummy) file 18be249b-fedf-4f54-a3ee-3275532e4221.tmp to /store/user/damram

INFO 2024-09-12 19:09:54.343 UTC: 	 Executing command: which scram >/dev/null 2>&1 && eval `scram unsetenv -sh`; gfal-copy -p -v -t 180 file:///gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/18be249b-fedf-4f54-a3ee-3275532e4221.tmp 'root://lyoeos.in2p3.fr:1094//store/user/damram/crab3checkwrite_20240912_210954_18be249b-fedf-4f54-a3ee-3275532e4221/18be249b-fedf-4f54-a3ee-3275532e4221.tmp'
INFO 2024-09-12 19:09:54.344 UTC: 	 Please wait...
INFO 2024-09-12 19:10:00.290 UTC: 	 Failed running copy command
INFO 2024-09-12 19:10:00.290 UTC: 	   Stdout:
    Copying 85 bytes file:///gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/18be249b-fedf-4f54-a3ee-3275532e4221.tmp => root://lyoeos.in2p3.fr:1094//store/user/damram/crab3checkwrite_20240912_210954_18be249b-fedf-4f54-a3ee-3275532e4221/18be249b-fedf-4f54-a3ee-3275532e4221.tmp
    event: [1726168199806] BOTH   GFAL2:CORE:COPY	LIST:ENTER	
    event: [1726168199806] BOTH   GFAL2:CORE:COPY	LIST:ITEM	file:///gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/18be249b-fedf-4f54-a3ee-3275532e4221.tmp => root://lyoeos.in2p3.fr:1094//store/user/damram/crab3checkwrite_20240912_210954_18be249b-fedf-4f54-a3ee-3275532e4221/18be249b-fedf-4f54-a3ee-3275532e4221.tmp
    event: [1726168199806] BOTH   GFAL2:CORE:COPY	LIST:EXIT	
    event: [1726168199808] BOTH   xroot	TRANSFER:ENTER	file://localhost///gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/18be249b-fedf-4f54-a3ee-3275532e4221.tmp?xrd.gsiusrpxy=/tmp/x509up_u2414&xrdcl.intent=tpc => root://lyoeos.in2p3.fr:1094///store/user/damram/crab3checkwrite_20240912_210954_18be249b-fedf-4f54-a3ee-3275532e4221/18be249b-fedf-4f54-a3ee-3275532e4221.tmp?xrd.gsiusrpxy=/tmp/x509up_u2414&xrdcl.intent=tpc
    event: [1726168199808] BOTH   xroot	TRANSFER:TYPE	streamed
    event: [1726168200211] BOTH   xroot	TRANSFER:EXIT	Job finished, [ERROR] Server responded with an error: [3010] Unable to access(XW) parent directory /eos/lyoeos.in2p3.fr/grid/cms/store/user/damram/; Operation not permitted (destination)
    
    event: [1726168200213] DEST   xroot	CLEANUP	0
    
INFO 2024-09-12 19:10:00.290 UTC: 	   Stderr:
    gfal-copy error: 13 (Permission denied) - Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [3010] Unable to access(XW) parent directory /eos/lyoeos.in2p3.fr/grid/cms/store/user/damram/; Operation not permitted (destination)
    
    
INFO 2024-09-12 19:10:00.291 UTC: 	 
Checkwrite Result:
INFO 2024-09-12 19:10:00.291 UTC: 	 Error: Unable to write in /store/user/damram on site T3_FR_IPNL
       You may want to contact the site administrators sending them the 'crab checkwrite' output as printed above.
INFO 2024-09-12 19:10:00.291 UTC: 	 Note: You cannot write to a site if you did not ask permission.
ERROR 2024-09-12 19:10:00.291 UTC: 	 Command checkwrite failed
ERROR 2024-09-12 19:10:00.292 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 139, in __call__
    raise CommandFailedException("Command %s failed" % str(args[0]))
CRABClient.ClientExceptions.CommandFailedException: Command checkwrite failed
DEBUG 2024-09-13 13:20:11.273 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-13 13:20:11.273 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-13 13:20:11.273 UTC: 	 Executing command: 'submit'
DEBUG 2024-09-13 13:20:11.274 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
INFO 2024-09-13 13:20:11.275 UTC: 	 Will use CRAB configuration file crab_config_data.py
DEBUG 2024-09-13 13:20:11.276 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-09-13 13:20:11.280 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-09-13 13:20:11.281 UTC: 	 Working area '/gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_2022G' already exists 
Please change the requestName in the config file
ERROR 2024-09-13 13:20:11.281 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 327, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_2022G' already exists 
Please change the requestName in the config file
INFO 2024-09-13 13:20:11.350 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-13 14:15:26.785 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-13 14:15:26.786 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-13 14:15:26.786 UTC: 	 Executing command: 'status'
DEBUG 2024-09-13 14:15:26.786 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
ERROR 2024-09-13 14:15:26.788 UTC: 	 Cannot find .requestcache file in CRAB project directory /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_2022G
ERROR 2024-09-13 14:15:26.788 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 684, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 525, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_2022G
INFO 2024-09-13 14:15:26.790 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-13 14:59:59.239 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-13 14:59:59.239 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-13 14:59:59.239 UTC: 	 Executing command: 'status'
DEBUG 2024-09-13 14:59:59.240 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
ERROR 2024-09-13 14:59:59.242 UTC: 	 Error: /chemin/vers/crab_projects/crab_EGamma_crab_MC_22G is not a valid CRAB project directory.
ERROR 2024-09-13 14:59:59.242 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: /chemin/vers/crab_projects/crab_EGamma_crab_MC_22G is not a valid CRAB project directory.
INFO 2024-09-13 14:59:59.270 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-13 18:18:07.480 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-13 18:18:07.481 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-13 18:18:07.481 UTC: 	 Executing command: 'submit'
DEBUG 2024-09-13 18:18:07.481 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
INFO 2024-09-13 18:18:07.482 UTC: 	 Will use CRAB configuration file crab_config_mc.py
DEBUG 2024-09-13 18:18:07.482 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-09-13 18:18:07.484 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-09-13 18:18:07.484 UTC: 	 Working area '/gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_MC_22G' already exists 
Please change the requestName in the config file
ERROR 2024-09-13 18:18:07.484 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 327, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_MC_22G' already exists 
Please change the requestName in the config file
INFO 2024-09-13 18:18:07.486 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-13 20:39:47.613 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-13 20:39:47.614 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-13 20:39:47.614 UTC: 	 Executing command: 'getlog'
DEBUG 2024-09-13 20:39:47.614 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
DEBUG 2024-09-14 08:16:15.116 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-14 08:16:15.117 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-14 08:16:15.117 UTC: 	 Executing command: 'status'
DEBUG 2024-09-14 08:16:15.117 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
ERROR 2024-09-14 08:16:15.119 UTC: 	 Error: /chemin/vers/crab_projects/crab_EGamma_crab_MC_22G is not a valid CRAB project directory.
ERROR 2024-09-14 08:16:15.119 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: /chemin/vers/crab_projects/crab_EGamma_crab_MC_22G is not a valid CRAB project directory.
INFO 2024-09-14 08:16:15.140 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-14 20:23:24.375 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-14 20:23:24.376 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-14 20:23:24.376 UTC: 	 Executing command: 'kill'
DEBUG 2024-09-14 20:23:24.376 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
DEBUG 2024-09-14 20:24:01.406 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-14 20:24:01.407 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-14 20:24:01.407 UTC: 	 Executing command: 'resubmit'
DEBUG 2024-09-14 20:24:01.407 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
DEBUG 2024-09-14 20:30:12.212 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-14 20:30:12.212 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-14 20:30:12.212 UTC: 	 Executing command: 'status'
DEBUG 2024-09-14 20:30:12.213 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
ERROR 2024-09-14 20:30:12.214 UTC: 	 Error: crab_projects/crab_EGamma_crab_2022G/ is not a valid CRAB project directory.
ERROR 2024-09-14 20:30:12.214 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_EGamma_crab_2022G/ is not a valid CRAB project directory.
INFO 2024-09-14 20:30:12.216 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-14 20:30:25.070 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-14 20:30:25.070 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-14 20:30:25.070 UTC: 	 Executing command: 'submit'
DEBUG 2024-09-14 20:30:25.070 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
DEBUG 2024-09-16 14:39:06.317 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-16 14:39:06.318 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-16 14:39:06.318 UTC: 	 Executing command: 'status'
DEBUG 2024-09-16 14:39:06.318 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
DEBUG 2024-09-16 19:36:46.613 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-16 19:36:46.613 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-16 19:36:46.613 UTC: 	 Executing command: 'submit'
DEBUG 2024-09-16 19:36:46.614 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
INFO 2024-09-16 19:36:46.615 UTC: 	 Will use CRAB configuration file crab_config_data.py
DEBUG 2024-09-16 19:36:46.615 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-09-16 19:36:46.620 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-09-16 19:36:46.620 UTC: 	 Working area '/gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_2022A' already exists 
Please change the requestName in the config file
ERROR 2024-09-16 19:36:46.620 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 327, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_2022A' already exists 
Please change the requestName in the config file
INFO 2024-09-16 19:36:46.643 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-16 20:12:30.604 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-16 20:12:30.604 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-16 20:12:30.604 UTC: 	 Executing command: 'status'
DEBUG 2024-09-16 20:12:30.604 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
ERROR 2024-09-16 20:12:30.605 UTC: 	 Error: crab_projects/crab_EGamma_crab_2022B is not a valid CRAB project directory.
ERROR 2024-09-16 20:12:30.606 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_EGamma_crab_2022B is not a valid CRAB project directory.
INFO 2024-09-16 20:12:30.607 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-16 20:42:43.082 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-16 20:42:43.083 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-16 20:42:43.083 UTC: 	 Executing command: 'submit'
DEBUG 2024-09-16 20:42:43.083 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
INFO 2024-09-16 20:42:43.085 UTC: 	 Will use CRAB configuration file crab_config_data.py
DEBUG 2024-09-16 20:42:43.085 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-09-16 20:42:43.089 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-09-16 20:42:43.090 UTC: 	 Working area '/gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_2022G' already exists 
Please change the requestName in the config file
ERROR 2024-09-16 20:42:43.090 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 327, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab_projects/crab_EGamma_crab_2022G' already exists 
Please change the requestName in the config file
INFO 2024-09-16 20:42:43.093 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-16 21:29:31.682 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-16 21:29:31.683 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-16 21:29:31.683 UTC: 	 Executing command: 'status'
DEBUG 2024-09-16 21:29:31.683 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
ERROR 2024-09-16 21:29:31.685 UTC: 	 Error: crab_projects/crab_EGamma_crab_2022B is not a valid CRAB project directory.
ERROR 2024-09-16 21:29:31.685 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_EGamma_crab_2022B is not a valid CRAB project directory.
INFO 2024-09-16 21:29:31.690 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
DEBUG 2024-09-17 10:05:57.830 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-09-17 10:05:57.830 UTC: 	 Running on: Linux lyoui4.in2p3.fr 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-09-17 10:05:57.830 UTC: 	 Executing command: 'status'
DEBUG 2024-09-17 10:05:57.831 UTC: 	 Found CRAB cache file /home/cms/amram/.crab3
ERROR 2024-09-17 10:05:57.832 UTC: 	 Error: crab_projects/crab_EGamma_crab_MC_22F is not a valid CRAB project directory.
ERROR 2024-09-17 10:05:57.833 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_EGamma_crab_MC_22F is not a valid CRAB project directory.
INFO 2024-09-17 10:05:57.835 UTC: 	 Log file is /gridgroup/cms/amram/EPR/CMSSW_13_3_3/src/ConeOptimisation/ConeOptimisation/python/crab.log
